MAIN_PAGE_WEIXIN_TEXT: '微信'
MAIN_PAGE_CONTACT_TEXT: '通讯录'
MAIN_PAGE_DISCOVER_TEXT: '发现'
MAIN_PAGE_ME_TEXT: '我'

ME_PAGE_MY_POST_TEXT: '相册'
MOMENT_PAGE_ME_TEXT: '我的相册'

MY_POST_PAGE_MOMENT_PIC_ID: 'com.tencent.mm:id/dep'
MY_POST_PAGE_MOMENT_ARTICLE_ID: 'com.tencent.mm:id/yk'


CONTACT_PAGE_SEARCH_BUTTON_ID: 'com.tencent.mm:id/jy'
OFFICIAL_ACCOUNTS_PAGE_ADD_BUTTON_ID: 'com.tencent.mm:id/jy'
SEARCH_PAGE_SEARCH_TEXT_BOX_ID: 'com.tencent.mm:id/kh'

OFFICIAL_ACCOUNTS_TEXT: '公众号'
MOMENT_DETAILED_PAGE_PRAISE_TEXT: '赞'
ENGLISH_QUOTE_NAME_TEXT: '英语短句每日分享'